### ISSUE TITLE
Install fairseq error

### ISSUE THREAD

**Issue by genbei** [teslacool/SCA#19]
pip install -r requirements.txt

![image](https://user-images.githubusercontent.com/57440758/88770844-f8646600-d1b0-11ea-827c-4272faa9a33e.png)

python setup.py build develop

and 
![image](https://user-images.githubusercontent.com/57440758/88750173-8297d480-d187-11ea-8101-c329be978b3b.png)

**Comment by teslacool** [comment]
Sorry for the late reply.

You should install  torch with version=0.4.1  (better use conda install).

**Comment by genbei** [comment]
The fairseq website pointed out that
PyTorch version &gt;= 1.4.0
Python version &gt;= 3.6
So I installed pytorch1.6 first
And I also downloaded torch 0.4.1 in pipinstall-r requirements.txt.
Excuse me, did you pay attention to anything during installation
And I can't use git clone





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "teslacool/SCA"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上8:28
收件人:&nbsp;"teslacool/SCA"<SCA@noreply.github.com&gt;;
抄送:&nbsp;"推杯换盏"<374481729@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [teslacool/SCA] Install fairseq error (#19)





 
Sorry for the late reply.
 
You should install  torch with version=0.4.1  (better use conda install).

**Comment by teslacool** [comment]
The fairseq website is the newest version, while our codebase is based on fairseq 0.6.0. So, the required pytorch versions are different.

When you installed torch 0.4.1 with pip, you got the error, "torch 0.4.1 not found". So I  suggest you to install it with conda.

**Comment by genbei** [comment]
Thank you very much for your answer. I see
Wish all the best





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "teslacool/SCA"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上9:55
收件人:&nbsp;"teslacool/SCA"<SCA@noreply.github.com&gt;;
抄送:&nbsp;"推杯换盏"<374481729@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [teslacool/SCA] Install fairseq error (#19)





 
The fairseq website is the newest version, while our codebase is based on fairseq 0.6.0. So, the required pytorch versions are different.
 
When you installed torch 0.4.1 with pip, you got the error, "torch 0.4.1 not found". So I  suggest you to install it with conda.
