### ISSUE TITLE
A little problem about IWSLT

### ISSUE THREAD

**Issue by genbei** [teslacool/SCA#20]
I have downloaded theIWSLT data, no problem
[Snipaste_2020-08-01_16-15-57](https://user-images.githubusercontent.com/57440758/89097540-678cc500-d412-11ea-9f05-266a5fbf79dd.png)
In addition
Did you add tag information to the results obtained in LM-sample experiment

**Comment by teslacool** [comment]
You'd better use the [file](https://github.com/teslacool/SCA/blob/master/examples/translation/prepare-iwslt14.sh) to prepare data.

I did not add tag information in LM-sample experiments.
