### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by genbei** [teslacool/SCA#21]
`Traceback (most recent call last):
  File "train.py", line 431, in <module>
    main(args)
  File "train.py", line 77, in main
    if args.load_lm:
AttributeError: 'Namespace' object has no attribute 'load_lm'`
When training the language model, I used the script you provided.and arch=transformer_lm
Why are there still mistakes
Besides, I don't quite understand your operation.
`src=en
tgt=ru
for l in $src $tgt; do
    srcdir=${src}2${tgt}
    tgtdir=lmof${l}
    mkdir -p $tgtdir
    cp $srcdir/dict.${l}.txt $tgtdir/dict.txt
    cp $srcdir/train.${src}-${tgt}.${l}.bin $tgtdir/train.bin
    cp $srcdir/train.${src}-${tgt}.${l}.idx $tgtdir/train.idx
    cp $srcdir/valid.${src}-${tgt}.${l}.bin $tgtdir/valid.bin
    cp $srcdir/valid.${src}-${tgt}.${l}.idx $tgtdir/valid.idx
done`
I didn't use the script you mentioned

**Comment by teslacool** [comment]
`src=en tgt=ru for l in $src $tgt; do srcdir=${src}2${tgt} tgtdir=lmof${l} mkdir -p $tgtdir cp $srcdir/dict.${l}.txt $tgtdir/dict.txt cp $srcdir/train.${src}-${tgt}.${l}.bin $tgtdir/train.bin cp $srcdir/train.${src}-${tgt}.${l}.idx $tgtdir/train.idx cp $srcdir/valid.${src}-${tgt}.${l}.bin $tgtdir/valid.bin cp $srcdir/valid.${src}-${tgt}.${l}.idx $tgtdir/valid.idx done`
This script will copy data for language modeling training.

please make sure that you use `--load_lm` flag in your script, and this will load language model checkpoint.

**Comment by genbei** [comment]
--load_lm，It's not in the sign of train.py, because he reminded me unrecongnized arguments
Then where can I use this flag


Thank you very much for replying to me, I am not familiar with this.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "teslacool/SCA"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 中午1:37
收件人:&nbsp;"teslacool/SCA"<SCA@noreply.github.com&gt;;
抄送:&nbsp;"推杯换盏"<374481729@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [teslacool/SCA] can you help me? (#21)





 
src=en tgt=ru for l in $src $tgt; do srcdir=${src}2${tgt} tgtdir=lmof${l} mkdir -p $tgtdir cp $srcdir/dict.${l}.txt $tgtdir/dict.txt cp $srcdir/train.${src}-${tgt}.${l}.bin $tgtdir/train.bin cp $srcdir/train.${src}-${tgt}.${l}.idx $tgtdir/train.idx cp $srcdir/valid.${src}-${tgt}.${l}.bin $tgtdir/valid.bin cp $srcdir/valid.${src}-${tgt}.${l}.idx $tgtdir/valid.idx done
 This script will copy data for language modeling training.
 
please make sure that you use --load_lm flag in your script, and this will load language model checkpoint.
