### ISSUE TITLE
Error training language model

### ISSUE THREAD

**Issue by genbei** [teslacool/SCA#22]
I'm very sorry to disturb you, because I haven't solved this problem.
I encountered the following problems when training the language model

`Traceback (most recent call last): File "train.py", line 431, in <module> main(args) File "train.py", line 77, in main if args.load_lm: AttributeError: 'Namespace' object has no attribute 'load_lm'
`
I use the same steps as you use,and arch=transformer_lm
`python train.py $DATA  --task language_modeling --arch $ARCH \
  --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
  --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
  --lr 0.0005 --min-lr 1e-09 \
  --dropout 0.1 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
  --max-tokens 4096  --tokens-per-sample 4096  --save-dir $SAVE --update-freq 16`

I noticed what you said
`I have modified this fairseq repo's dataloader, you'd better train language models with standard fairseq repo.`
but I don’t know how to use standard fairseq. I can’t train on the current version because of the problem with the pytorch version. Later I downloaded the code of fairseq 0.6.0 and there are problems with it. I really It is impossible to train the language model, can you tell me the steps you train
![1805](https://user-images.githubusercontent.com/57440758/89733116-dbb81000-da85-11ea-8c99-d859cefa180d.png)

**Comment by teslacool** [comment]
https://github.com/pytorch/pytorch/issues/7548
