### ISSUE TITLE
Problem of training efficiency

### ISSUE THREAD

**Issue by pemywei** [teslacool/SCA#7]
Dear author. Thanks very much for your work. I have a question, in my experiment, the training speed of lm-nmt is much slower than that of pure nmt model, is it common?

**Comment by teslacool** [comment]
Because every forward procedure, the models have been deeper than a pure one. So the training speed will be slower. And in my exps, the training epochs needed for modes to be convergent are also increased, so are other data augmentation methods.

**Comment by pemywei** [comment]
Thanks for your reply.
