### ISSUE TITLE
Pull Request into fairseq

### ISSUE THREAD

**Issue by nicolabertoldi** [teslacool/SCA#8]
@teslacool 

I am really impressed about your work, and I think it would be very useful for everyone (and for me in particular) having it inside fairseq.
Did you intend to make a Pull Request?
If you prefer, I volunteer to do it.

**Comment by teslacool** [comment]
Thank you very much for your interest and I am very happy that this work is useful for you.

I would appreciate it if  you are willing to help me make a pull request because I am not very familiar with this github process.

**Comment by nicolabertoldi** [comment]
@teslacool 

fantastic,
 I will take care to prepare the pull request into fairseq

I would like to know when you forked your repo from the fairseq.
Just to know how far/close is your code from the current fairseq.

**Comment by teslacool** [comment]
I have keep the commit history, so from the [commit page](https://github.com/teslacool/SCA/commits/master), you can get the exact time stamp : ).
